Rewrite CredentialsFragment to compose
ArnyminerZ/icsx5 pull request #26
Opened 2023-12-06 10:53 UTC by sunkup

Note that theming is missing on purpose

2023-12-06 13:25 UTC, ArnyminerZ requested changes
Instead of using XML drawables, it's better to use the built-in `Icons.*.*` icons. They are `ImageVector`s, which are more optimized.

However, by default Compose doesn't bundle all the icons from Google Fonts, for that you need Material Icons Extended:
```groovy
dependencies {
  implementation "androidx.compose.material:material-icons-extended:$compose_version"
}
```

It might seem like a lot of extra icons, and unwanted app size increase, but as far as I've read, Android does a great job on getting rid of the unused icons.

See [the documentation](https://developer.android.com/jetpack/compose/graphics/images/material) for icons in Compose.

2023-12-07 12:08 UTC, sunkup commented
> See [the documentation](https://developer.android.com/jetpack/compose/graphics/images/material) for icons in Compose.

It says:
> It's worth noting that it's not required to use Icon to render a VectorDrawable on screen, under the hood, Icon uses Modifier.paint(painterResource(R.drawable.ic_bus_stop)) to draw the Icon on screen. For more information on all the available icons, take a look at the [Icons documentation](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary).

So it sounds like it does the exact same thing, no? Which part is more optimized? :)

Also consider the following:
From the [Icons documentation](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary):
> A separate library, androidx.compose.material:material-icons-extended, contains the full set of Material icons. Due to the very large size of this library, make sure to use R8/Proguard to strip unused icons if you are including this library as a direct dependency. Alternatively you can make a local copy (by copy and pasting) the icon(s) you wish to keep, or using Android Studio's 'Import vector asset' feature.

I guess because we are using proguard already we can include the extended icon set too though, since proguard will automatically do the "resource shrinking". And using the library icons is probably less bothersome in the long run.

Let's do it :+1:

2023-12-09 10:51 UTC, ArnyminerZ approved these changes

2023-12-09 10:52 UTC, ArnyminerZ commented
> And using the library icons is probably less bothersome in the long run.

Yeah, I mean, if we are trying to get rid of XML it's better if we do everything with Compose

2023-12-11 10:25 UTC, merged