Migrate `AddCalendarActivity` to Jetpack Compose
ArnyminerZ/icsx5 pull request #45
Opened 2024-01-11 10:10 UTC by ArnyminerZ

Sorry for the big PR, but splitting it into two added even more code, since a library has to be used to import the Fragment into Compose. I hope it's not a big issue 😅

2024-01-11 11:53 UTC, sunkup requested changes
> Sorry for the big PR, but splitting it into two added even more code, since a library has to be used to import the Fragment into Compose. I hope it's not a big issue 😅

No, its actually very doable. Most of the changes are very straightforward :)


But it does not seem to be working? I am getting lots of exceptions and I can't add any subscriptions ...

```
12:49:32.495  E  Couldn't create calendar
                 java.lang.NullPointerException
                 	at at.bitfire.icsdroid.model.SubscriptionModel$create$1.invokeSuspend(SubscriptionModel.kt:38)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
12:49:32.500  D  Compat change id reported: 147798919; UID 10194; state: ENABLED
--------- beginning of crash
12:49:32.500  D  Shutting down VM
12:49:32.505  E  FATAL EXCEPTION: main
                 Process: at.bitfire.icsdroid, PID: 4915
                 java.lang.IllegalStateException: You must either set a text or a view
                 	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
                 	at android.widget.Toast.show(Toast.java:199)
                 	at at.bitfire.icsdroid.ui.AddCalendarActivity$onCreate$3.invoke(AddCalendarActivity.kt:118)
                 	at at.bitfire.icsdroid.ui.AddCalendarActivity$onCreate$3.invoke(AddCalendarActivity.kt:117)
                 	at at.bitfire.icsdroid.ui.AddCalendarActivity$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                 	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

Edit: Now I could add a subscription, but the subscription name is the exception? :thinking: 

![image](https://github.com/ArnyminerZ/icsx5/assets/8227414/c9ebad24-99b8-4f2f-8aa8-f7109297c2d0)

2024-01-11 14:06 UTC, ArnyminerZ commented
🤔 I'll take a look, but it was working fine for me

2024-01-11 14:16 UTC, ArnyminerZ commented
It's working for me on emulator API 31 and 34, in two different computers, and on my testing device (Xiaomi Mi A2 API 29) 🤔 

Can you try building again? Clearing caches or something? Also the errors are pretty strange

2024-01-11 14:36 UTC, sunkup commented
> It's working for me on emulator API 31 and 34, in two different computers, and on my testing device (Xiaomi Mi A2 API 29) 🤔
> 
> Can you try building again? Clearing caches or something? Also the errors are pretty strange

Ah, yes. Not sure why the quirks happened ... Will review now, but prob. not ready till Monday :)

2024-01-15 12:53 UTC, sunkup approved these changes
Looks good :)

2024-01-15 12:53 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt
> +@OptIn(ExperimentalFoundationApi::class)
What is this doing? Do we need it?

> This foundation API is experimental and is likely to change or be removed in the future

Sounds dangerous :sweat_smile:

2024-01-15 12:53 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarActivity.kt
> +@OptIn(ExperimentalFoundationApi::class)
Ah, its for this one
https://developer.android.com/jetpack/compose/layouts/pager

Hmm, I guess we really have to use it ... Would have thought compose to be more mature ...

2024-01-15 12:54 UTC, merged