Cleanup of Dialogs
ArnyminerZ/icsx5 pull request #67
Opened 2024-01-24 13:45 UTC by ArnyminerZ

2024-01-25 10:46 UTC, sunkup requested changes
Does not work :(

Now every time I enter the EditSubscriptionActivity, it tells me there are unsaved changes.

2024-01-25 13:16 UTC, ArnyminerZ commented
My bad, I had a stupid typo

2024-01-25 14:09 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/dialog/AlertDialogBox.kt
I don't think using `AlertDialogBox` to wrap `GenericAlertDialog` while adding only the Text() composable is worth it. I think we can safely use `GenericAlertDialog` everywhere and delete this file.

2024-01-25 14:20 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/dialog/GenericAlertDialog.kt
> +        // FIXME : I don't love this syntax, but I'm not sure if there's a cleaner way...
I don't think it's too bad :) Nearly looks like handlebar template engine :+1: 

Would probably make it all go on one line though ;)

2024-01-25 14:22 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/dialog/SyncIntervalDialog.kt
> +@OptIn(ExperimentalMaterialApi::class)
Wow. Why are list items still expermental? :D

2024-01-25 14:33 UTC, sunkup commented on app/src/main/java/at/bitfire/icsdroid/ui/dialog/GenericAlertDialog.kt
> +interface AlertDialogContext {
Really cool, that this is possible and good to know. But I feel the complexity it adds in comparison do the benefit it brings is too small. I would keep this for more complicated compose setups and stick with the simple tools for now.

2024-01-25 14:35 UTC, sunkup requested changes
See comments :)

2024-01-30 09:55 UTC, sunkup approved these changes
Nice ~

2024-01-30 09:55 UTC, merged